# https://help.github.com/en/articles/metadata-syntax-for-github-actions

name: 'kaowao-scan'
description: 'scans for file modifications and alerts uppon changes'
author: '@OccamsLabs'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  args:
    description: 'Arguments for kaowao'
    required: true
    default: '-h'

runs:
  using: 'docker'
  image: "docker://ghcr.io/occamslabs/kaowao:latest"
  args:
    - ${{ inputs.args }}


