# action.yml
name: 'kaowao scanner'
description: 'scans for file modifications and alerts'
inputs:
    args:
    description: 'Arguments for kaowao'
    required: true
    default: '-h'

runs:
  using: 'docker'
  image: "docker://OccamsLabs/kaowao:latest"
  args:
    - ${{ inputs.args }}


branding:
  icon: 'shield'
  color: 'blue'
